add_newline = false
format = """
$directory\
$git_branch\
$git_status\
$character\
$cmd_duration"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[directory]
format = "[$path]($style)(bold blue)[$read_only](bold #F0FF42)($read_only_style) "
truncation_length = 4
truncation_symbol = '…/'
home_symbol = "  "
read_only = "  "

[git_branch]
style = "bold #7C83FD"

[git_metrics]
disabled = false

[git_status]
ahead = " ⇡ ${count}"
diverged = "⇕ ⇡ ${ahead_count} ⇣ ${behind_count}"
behind = "⇣ ${count}"
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "#ff00dd"

[cmd_duration]
disabled = false
format = "[$duration]($style) "
style = "yellow"
